**Implementing AND Gate in Neural Network **

In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

**Assign Input Values**

In [2]:
input_val=np.array([[0,0],[0,1],[1,1],[1,0]])
input_val.shape

(4, 2)

**Assign Output Values**

In [3]:
output=np.array([0,0,1,0])
output=output.reshape(4,1)
output.shape

(4, 1)

**Assign Weights**

In [4]:
weights=np.array([[0.1], [0.2]])
weights

array([[0.1],
       [0.2]])

**Adding Bias**

In [5]:
bias=0.3

**Activation Function**

In [6]:
def sigmoid_func(x):
  return 1/(1+np.exp(-x))

**Derivative of sigmoid function**

In [7]:
def der(x):
  return sigmoid_func(x) * (1-sigmoid_func(x))

**Updating weights**

In [19]:
for epochs in range(10000):
  input_arr = input_val

  weighted_sum = np.dot(input_arr, weights) + bias
  first_output = sigmoid_func(weighted_sum)

  error = first_output - output
  total_error = np.square(np.subtract(first_output,output)).mean()
  #print(total_error)

  first_der = error
  second_der = der(first_output)
  derivative = first_der * second_der

  t_input = input_val.T
  final_derivative = np.dot(t_input,derivative)

  #update weights
  weights=weights - 0.04 * final_derivative

  #update bias
  for i in derivative:
    bias = bias - 0.01 * i

  print(weights)
  print(bias)


Streaming output truncated to the last 5000 lines.
 [7.95437373]]
[-3.43223105]
[[7.9543378 ]
 [7.95445872]]
[-3.4322668]
[[7.95442279]
 [7.9545437 ]]
[-3.43230255]
[[7.95450778]
 [7.95462867]]
[-3.4323383]
[[7.95459276]
 [7.95471364]]
[-3.43237405]
[[7.95467773]
 [7.95479861]]
[-3.4324098]
[[7.95476271]
 [7.95488357]]
[-3.43244555]
[[7.95484768]
 [7.95496853]]
[-3.4324813]
[[7.95493264]
 [7.95505348]]
[-3.43251705]
[[7.9550176 ]
 [7.95513844]]
[-3.43255279]
[[7.95510256]
 [7.95522338]]
[-3.43258854]
[[7.95518751]
 [7.95530832]]
[-3.43262429]
[[7.95527246]
 [7.95539326]]
[-3.43266003]
[[7.9553574]
 [7.9554782]]
[-3.43269577]
[[7.95544234]
 [7.95556312]]
[-3.43273152]
[[7.95552728]
 [7.95564805]]
[-3.43276726]
[[7.95561221]
 [7.95573297]]
[-3.432803]
[[7.95569714]
 [7.95581789]]
[-3.43283875]
[[7.95578206]
 [7.9559028 ]]
[-3.43287449]
[[7.95586698]
 [7.95598771]]
[-3.43291023]
[[7.95595189]
 [7.95607262]]
[-3.43294597]
[[7.9560368 ]
 [7.95615752]]
[-3.43298171]
[[7.95612171]
 [7.9562424

In [20]:
pred = np.array([0,1])
result=np.dot(pred, weights) + bias
res=sigmoid_func(result)
print(res)

[0.99004512]


**Implementing OR Gate using Neural Network**

In [11]:
input_val=np.array([[0,0],[0,1],[1,1],[1,0]])
input_val.shape

(4, 2)

**Assigning Output Values**

In [12]:
output=np.array([0,1,1,1])
output=output.reshape(4,1)
output.shape

(4, 1)

**Assigning Weights**

In [13]:
weights=np.array([[0.1], [0.2]])
weights

array([[0.1],
       [0.2]])

**Adding Bias**

In [14]:
bias=0.3

**Activation Function**

In [15]:
def sigmoid_func(x):
  return 1/(1+np.exp(-x))

In [16]:
def der(x):
  return sigmoid_func(x) * (1-sigmoid_func(x))

**Updating Weights**

In [21]:
for epochs in range(10000):
  input_arr = input_val

  weighted_sum = np.dot(input_arr, weights) + bias
  first_output = sigmoid_func(weighted_sum)

  error = first_output - output
  total_error = np.square(np.subtract(first_output,output)).mean()
  #print(total_error)

  first_der = error
  second_der = der(first_output)
  derivative = first_der * second_der

  t_input = input_val.T
  final_derivative = np.dot(t_input,derivative)

  #update weights
  weights=weights - 0.04 * final_derivative

  #update bias
  for i in derivative:
    bias = bias - 0.01 * i

  print(weights)
  print(bias)


Streaming output truncated to the last 5000 lines.
 [8.6519479 ]]
[-3.75186975]
[[8.65194583]
 [8.65200624]]
[-3.75189792]
[[8.65200417]
 [8.65206457]]
[-3.75192608]
[[8.6520625]
 [8.6521229]]
[-3.75195425]
[[8.65212084]
 [8.65218123]]
[-3.75198241]
[[8.65217917]
 [8.65223956]]
[-3.75201057]
[[8.6522375 ]
 [8.65229788]]
[-3.75203873]
[[8.65229582]
 [8.65235621]]
[-3.75206689]
[[8.65235415]
 [8.65241453]]
[-3.75209506]
[[8.65241247]
 [8.65247285]]
[-3.75212322]
[[8.6524708 ]
 [8.65253117]]
[-3.75215137]
[[8.65252912]
 [8.65258949]]
[-3.75217953]
[[8.65258743]
 [8.6526478 ]]
[-3.75220769]
[[8.65264575]
 [8.65270611]]
[-3.75223585]
[[8.65270407]
 [8.65276443]]
[-3.752264]
[[8.65276238]
 [8.65282274]]
[-3.75229216]
[[8.65282069]
 [8.65288104]]
[-3.75232031]
[[8.652879  ]
 [8.65293935]]
[-3.75234847]
[[8.65293731]
 [8.65299766]]
[-3.75237662]
[[8.65299562]
 [8.65305596]]
[-3.75240477]
[[8.65305392]
 [8.65311426]]
[-3.75243293]
[[8.65311222]
 [8.65317256]]
[-3.75246108]
[[8.65317053]
 [8.653

In [18]:
pred = np.array([0,1])
result=np.dot(pred, weights) + bias
res=sigmoid_func(result)
print(res)

[0.97937643]
